# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Simsies
tagline:          'Artist/Scholar'
description:      ''
url:              http://jcpsimmons.github.io
baseurl:          /

author:
  name:           'Josh Simmons'
  url:            https://simsies.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
